/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class element_io_base_NativeFunction */

#ifndef _Included_element_io_base_NativeFunction
#define _Included_element_io_base_NativeFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     element_io_base_NativeFunction
 * Method:    date
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_element_io_base_NativeFunction_date
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
